// TASK LIST
export const ACTION_TASKS_FIND_TASK_LIST_REQUESTED = 'app/Tasks/ACTION_TASKS_FIND_TASK_LIST_REQUESTED';
export const ACTION_TASKS_FIND_TASK_LIST_SUCCEEDED = 'app/Tasks/ACTION_TASKS_FIND_TASK_LIST_SUCCEEDED';
export const ACTION_TASKS_FIND_TASK_LIST_FAILED = 'app/Tasks/ACTION_TASKS_FIND_TASK_LIST_FAILED';
export const ACTION_TASKS_CHANGE_CATEGORY = 'app/Tasks/ACTION_TASKS_CHANGE_CATEGORY';
